Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision "shell", inline: "sudo groupadd docker"
  config.vm.provision "shell", inline: "sudo usermod -aG docker #{USER_NAME}"
  config.vm.provision "shell", inline: "sudo --user #{USER_NAME} /vagrant/install_fabric.sh #{USER_NAME} > /dev/null 2>&1"
end
